# Example values for using AWS Secrets Manager with External Secrets
# This is a YAML-formatted file.

# Standard image configuration  
image:
  repository: your-registry.com/jitsi-recording-uploader
  tag: latest

# Use external secrets with AWS Secrets Manager
credentials:
  method: externalSecret
  externalSecret:
    name: jitsi-uploader-external-secret
    secretName: jitsi-uploader-credentials
    secretStore:
      name: aws-secrets-store
      kind: ClusterSecretStore  # Using ClusterSecretStore for AWS
    data:
      - secretKey: GOOGLE_CLIENT_ID
        remoteRef:
          key: jitsi-uploader/google-drive-credentials
          property: client-id
      - secretKey: GOOGLE_CLIENT_SECRET
        remoteRef:
          key: jitsi-uploader/google-drive-credentials
          property: client-secret
      - secretKey: GOOGLE_REFRESH_TOKEN
        remoteRef:
          key: jitsi-uploader/google-drive-credentials
          property: refresh-token

config:
  jibri:
    pvcName: "jibri-recordings-pvc"
  googleDrive:
    uploadFolderId: "your-folder-id"

# Example ClusterSecretStore configuration (apply separately):
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: aws-secrets-store
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: us-west-2
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: jitsi-recording-uploader
#             namespace: jitsi

# Example AWS IAM policy for the service account:
# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Action": [
#         "secretsmanager:GetSecretValue",
#         "secretsmanager:DescribeSecret"
#       ],
#       "Resource": "arn:aws:secretsmanager:us-west-2:123456789012:secret:jitsi-uploader/*"
#     }
#   ]
# }