# Example values for using HashiCorp Vault with External Secrets
# This is a YAML-formatted file.

# Standard image configuration
image:
  repository: your-registry.com/jitsi-recording-uploader
  tag: latest

# Use external secrets with Vault
credentials:
  method: externalSecret
  externalSecret:
    name: jitsi-uploader-external-secret
    secretName: jitsi-uploader-credentials
    secretStore:
      name: vault-secret-store
      kind: SecretStore
    data:
      - secretKey: GOOGLE_CLIENT_ID
        remoteRef:
          key: secret/google-drive/jitsi-uploader
          property: client-id
      - secretKey: GOOGLE_CLIENT_SECRET
        remoteRef:
          key: secret/google-drive/jitsi-uploader
          property: client-secret
      - secretKey: GOOGLE_REFRESH_TOKEN
        remoteRef:
          key: secret/google-drive/jitsi-uploader
          property: refresh-token

config:
  jibri:
    pvcName: "jibri-recordings-pvc"
  googleDrive:
    uploadFolderId: "your-folder-id"

# Example SecretStore configuration (apply separately):
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: vault-secret-store
#   namespace: jitsi
# spec:
#   provider:
#     vault:
#       server: "https://vault.example.com"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "jitsi-uploader"
#           serviceAccountRef:
#             name: jitsi-recording-uploader