# Production values for jitsi-recording-uploader
# This is a YAML-formatted file.

# Image configuration for production
image:
  repository: your-registry.com/jitsi-recording-uploader
  tag: v1.0.0
  pullPolicy: IfNotPresent

# Registry credentials for private registries
imagePullSecrets:
  - name: registry-credentials

# Production resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Use external secrets in production
credentials:
  method: externalSecret
  externalSecret:
    name: jitsi-uploader-external-secret
    secretName: jitsi-uploader-credentials
    secretStore:
      name: vault-secret-store
      kind: SecretStore
    data:
      - secretKey: GOOGLE_CLIENT_ID
        remoteRef:
          key: production/google-drive/jitsi-uploader
          property: client-id
      - secretKey: GOOGLE_CLIENT_SECRET
        remoteRef:
          key: production/google-drive/jitsi-uploader
          property: client-secret
      - secretKey: GOOGLE_REFRESH_TOKEN
        remoteRef:
          key: production/google-drive/jitsi-uploader
          property: refresh-token

# Production configuration
config:
  jibri:
    pvcName: "production-jibri-recordings"
  googleDrive:
    uploadFolderId: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74mHvn"
  app:
    logLevel: "warn"
    cleanupAfterUpload: true
    maxRetries: 5

# Enable monitoring in production
monitoring:
  enabled: true
  labels:
    prometheus: "production"
    environment: "prod"
  interval: 30s

# Pod disruption budget for availability
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Security context
podSecurityContext:
  fsGroup: 1001
  runAsNonRoot: true

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false

# Scheduling for RWO PVCs - ensure same node as Jibri
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values: ["jibri"]
      topologyKey: kubernetes.io/hostname

# Production-specific annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
  prometheus.io/path: "/metrics"

# Probes configuration
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readiness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3