apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-recording-uploader
  namespace: jitsi
  labels:
    app: jitsi-recording-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitsi-recording-uploader
  template:
    metadata:
      labels:
        app: jitsi-recording-uploader
    spec:
      # Schedule on the same node as Jibri pods
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["jibri"]  # Update to match your Jibri pod labels
            topologyKey: kubernetes.io/hostname
      containers:
      - name: uploader
        image: jitsi-recording-uploader:latest
        imagePullPolicy: Always
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: jitsi-uploader-credentials
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: jitsi-uploader-credentials
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: jitsi-uploader-credentials
              key: GOOGLE_REFRESH_TOKEN
        envFrom:
        - configMapRef:
            name: jitsi-uploader-config
        volumeMounts:
        - name: recordings-volume
          mountPath: /recordings
          readOnly: true  # Critical: read-only mount for RWO PVC
        - name: logs-volume
          mountPath: /app/logs
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - node
            - -e
            - "console.log('Health check passed')"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - node
            - -e
            - "console.log('Ready check passed')"
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: recordings-volume
        persistentVolumeClaim:
          claimName: jibri-recordings-pvc
          readOnly: true  # Explicitly set PVC as read-only
      - name: logs-volume
        emptyDir: {}
      restartPolicy: Always