apiVersion: v1
kind: ServiceAccount
metadata:
  name: jitsi-recording-uploader
  namespace: jitsi  # Change to your namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jitsi  # Change to your namespace
  name: jitsi-recording-uploader
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jitsi-recording-uploader
  namespace: jitsi  # Change to your namespace
subjects:
- kind: ServiceAccount
  name: jitsi-recording-uploader
  namespace: jitsi
roleRef:
  kind: Role
  name: jitsi-recording-uploader
  apiGroup: rbac.authorization.k8s.io