{{- if eq .Values.credentials.method "externalSecret" }}
{{- include "jitsi-recording-uploader.validateValues" . }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.credentials.externalSecret.name }}
  labels:
    {{- include "jitsi-recording-uploader.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.credentials.externalSecret.secretStore.name }}
    kind: {{ .Values.credentials.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.credentials.externalSecret.secretName }}
    creationPolicy: Owner
    type: Opaque
  data:
  {{- range .Values.credentials.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      {{- if .remoteRef.property }}
      property: {{ .remoteRef.property }}
      {{- end }}
  {{- end }}
{{- end }}